//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePointExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharePointExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCancel {
            get {
                return ResourceManager.GetString("MsgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cacnel to edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCancelCheckout {
            get {
                return ResourceManager.GetString("MsgCancelCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCanceling {
            get {
                return ResourceManager.GetString("MsgCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checked out user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCheckedOutUser {
            get {
                return ResourceManager.GetString("MsgCheckedOutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End to edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCheckin {
            get {
                return ResourceManager.GetString("MsgCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Begin to edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCheckout {
            get {
                return ResourceManager.GetString("MsgCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Cache に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgClearCache {
            get {
                return ResourceManager.GetString("MsgClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgClose {
            get {
                return ResourceManager.GetString("MsgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgConfirm {
            get {
                return ResourceManager.GetString("MsgConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local file has been modified . Do you want to continue to cancel ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgConfirmCacnelEditing {
            get {
                return ResourceManager.GetString("MsgConfirmCacnelEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If the you have to stop the upload , partially uploaded files might be placed in the server . Do you want to continue the stop ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgConfirmCancelUpload {
            get {
                return ResourceManager.GetString("MsgConfirmCancelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On both the local and server { 0 } has been changed . Do you want to overwrite the local in the downloaded file ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgConfirmDownloadOnEditing {
            get {
                return ResourceManager.GetString("MsgConfirmDownloadOnEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   local {0} file was edited. Are you sure you want to delete it ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgConfirmPrurgeCache {
            get {
                return ResourceManager.GetString("MsgConfirmPrurgeCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local file has been modified . Are you sure that you want to upload before completing the editing ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgConfirmUpload {
            get {
                return ResourceManager.GetString("MsgConfirmUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgConnect {
            get {
                return ResourceManager.GetString("MsgConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCopy {
            get {
                return ResourceManager.GetString("MsgCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Url to clipboard  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCopyUrlToClipBoard {
            get {
                return ResourceManager.GetString("MsgCopyUrlToClipBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCreate {
            get {
                return ResourceManager.GetString("MsgCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCreateFolder {
            get {
                return ResourceManager.GetString("MsgCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCut {
            get {
                return ResourceManager.GetString("MsgCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDateFormat {
            get {
                return ResourceManager.GetString("MsgDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDelete {
            get {
                return ResourceManager.GetString("MsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete {0}? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is the edited file . You need to upload . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDirtyConfirmUpoad {
            get {
                return ResourceManager.GetString("MsgDirtyConfirmUpoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDisconnect {
            get {
                return ResourceManager.GetString("MsgDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} downloading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDownloading {
            get {
                return ResourceManager.GetString("MsgDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDuplicateConnection {
            get {
                return ResourceManager.GetString("MsgDuplicateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit connection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgEditConnection {
            get {
                return ResourceManager.GetString("MsgEditConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExit {
            get {
                return ResourceManager.GetString("MsgExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFile {
            get {
                return ResourceManager.GetString("MsgFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFolder {
            get {
                return ResourceManager.GetString("MsgFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFormat {
            get {
                return ResourceManager.GetString("MsgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid target folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgInvalidMoveTargetFolder {
            get {
                return ResourceManager.GetString("MsgInvalidMoveTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register license key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgLicenseKey {
            get {
                return ResourceManager.GetString("MsgLicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgModifiedDate {
            get {
                return ResourceManager.GetString("MsgModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMove {
            get {
                return ResourceManager.GetString("MsgMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete {0} files? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgMultiDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgMultiDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgName {
            get {
                return ResourceManager.GetString("MsgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NewFolder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgNewFolder {
            get {
                return ResourceManager.GetString("MsgNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgOpen {
            get {
                return ResourceManager.GetString("MsgOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open web site に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgOpenWebSite {
            get {
                return ResourceManager.GetString("MsgOpenWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Owner に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgOwner {
            get {
                return ResourceManager.GetString("MsgOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgPassword {
            get {
                return ResourceManager.GetString("MsgPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgPaste {
            get {
                return ResourceManager.GetString("MsgPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgProcessing {
            get {
                return ResourceManager.GetString("MsgProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgRefresh {
            get {
                return ResourceManager.GetString("MsgRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgRename {
            get {
                return ResourceManager.GetString("MsgRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgRenameFolder {
            get {
                return ResourceManager.GetString("MsgRenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSave {
            get {
                return ResourceManager.GetString("MsgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSeacrhModeAll {
            get {
                return ResourceManager.GetString("MsgSeacrhModeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSearch {
            get {
                return ResourceManager.GetString("MsgSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSearchMode {
            get {
                return ResourceManager.GetString("MsgSearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSearchModeFolder {
            get {
                return ResourceManager.GetString("MsgSearchModeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Found. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSearchNotFound {
            get {
                return ResourceManager.GetString("MsgSearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search results に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSearchResults {
            get {
                return ResourceManager.GetString("MsgSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgShowUrl {
            get {
                return ResourceManager.GetString("MsgShowUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SharePoint URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSiteUrl {
            get {
                return ResourceManager.GetString("MsgSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSize {
            get {
                return ResourceManager.GetString("MsgSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgTargetFolder {
            get {
                return ResourceManager.GetString("MsgTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUpload {
            get {
                return ResourceManager.GetString("MsgUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} uploading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUploading {
            get {
                return ResourceManager.GetString("MsgUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUser {
            get {
                return ResourceManager.GetString("MsgUser", resourceCulture);
            }
        }
    }
}
